use_frameworks!

platform :ios, '8.0'

target 'BinartOCThreadSafeContainers_Example' do
  pod 'BinartOCThreadSafeContainers', :path => '../'

  target 'BinartOCThreadSafeContainers_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
